/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as ProveedoresRouteImport } from './routes/proveedores'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as BandejaRouteImport } from './routes/bandeja'
import { Route as IndexRouteImport } from './routes/index'

const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProveedoresRoute = ProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const BandejaRoute = BandejaRouteImport.update({
  id: '/bandeja',
  path: '/bandeja',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bandeja': typeof BandejaRoute
  '/catalogo': typeof CatalogoRoute
  '/proveedores': typeof ProveedoresRoute
  '/recursos': typeof RecursosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bandeja': typeof BandejaRoute
  '/catalogo': typeof CatalogoRoute
  '/proveedores': typeof ProveedoresRoute
  '/recursos': typeof RecursosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bandeja': typeof BandejaRoute
  '/catalogo': typeof CatalogoRoute
  '/proveedores': typeof ProveedoresRoute
  '/recursos': typeof RecursosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bandeja' | '/catalogo' | '/proveedores' | '/recursos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bandeja' | '/catalogo' | '/proveedores' | '/recursos'
  id: '__root__' | '/' | '/bandeja' | '/catalogo' | '/proveedores' | '/recursos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BandejaRoute: typeof BandejaRoute
  CatalogoRoute: typeof CatalogoRoute
  ProveedoresRoute: typeof ProveedoresRoute
  RecursosRoute: typeof RecursosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proveedores': {
      id: '/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof ProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bandeja': {
      id: '/bandeja'
      path: '/bandeja'
      fullPath: '/bandeja'
      preLoaderRoute: typeof BandejaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BandejaRoute: BandejaRoute,
  CatalogoRoute: CatalogoRoute,
  ProveedoresRoute: ProveedoresRoute,
  RecursosRoute: RecursosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
